"""Curated Core Engine Operations (Node, Scene, Script, Resource, Filesystem, Project, Session, Editor)."""

from __future__ import annotations

from godot_omni.operations.builder import op
from godot_omni.registry.models import (
    CanonicalOperation,
    ExecutionContext,
    LatencyTier,
    OperationCategory,
    ReadWrite,
)


def get_curated_core_operations() -> list[CanonicalOperation]:
    ops: list[CanonicalOperation] = [
        # --- SESSION ---
        op(
            "session.list",
            "List Connected Godot Sessions",
            "List all connected Godot editor and game sessions with their project paths, engine versions, and status.",
            "session",
            read_write=ReadWrite.READ,
            aliases=["session_list", "sessions.list"],
            examples=[("List all sessions", {}, {"sessions": [{"id": "my_proj@1234", "project": "MyProject"}]})],
        ),
        op(
            "session.activate",
            "Activate / Pin Target Session",
            "Pin subsequent MCP tool invocations to a specific connected Godot editor or game session.",
            "session",
            read_write=ReadWrite.WRITE,
            params=[("session_id", "string", "Target session ID or project substring match", True, None, [])],
            aliases=["session_activate"],
        ),
        op(
            "session.diagnostics",
            "Get Session Diagnostics & Latency",
            "Retrieve network latency, connection status, queue backlog, and memory metrics for the active session.",
            "session",
            read_write=ReadWrite.READ,
            aliases=["session_diagnostics"],
        ),
        op(
            "session.disconnect",
            "Disconnect Active Session",
            "Gracefully detach the server from the current Godot editor session.",
            "session",
            read_write=ReadWrite.WRITE,
            aliases=["session_disconnect"],
        ),

        # --- EDITOR ---
        op(
            "editor.get_state",
            "Get Editor State & Readiness",
            "Retrieve editor version, active project name, current scene, editability status, and running game status.",
            "editor",
            read_write=ReadWrite.READ,
            aliases=["editor_state", "get_editor_state"],
            examples=[("Check editor state", {}, {"project_name": "Game", "current_scene": "res://main.tscn", "is_ready": True})],
        ),
        op(
            "editor.selection.get",
            "Get Current Node/Resource Selection",
            "Retrieve the currently selected nodes or resources in the Godot editor hierarchy/dock.",
            "editor",
            read_write=ReadWrite.READ,
            aliases=["get_selection", "editor_get_selection"],
        ),
        op(
            "editor.selection.set",
            "Set Selected Nodes in Editor",
            "Set the active node selection in the Godot scene tree dock by node paths.",
            "editor",
            read_write=ReadWrite.WRITE,
            params=[
                ("paths", "array", "List of node paths to select", True, None, []),
                ("clear_existing", "boolean", "Whether to clear existing selection first", False, True, []),
            ],
            aliases=["set_selection", "editor_set_selection"],
        ),
        op(
            "editor.screenshot",
            "Capture Editor or Game Viewport",
            "Capture a visual screenshot of the 3D viewport, 2D viewport, running game framebuffer, or cinematic camera.",
            "editor",
            read_write=ReadWrite.READ,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[
                ("source", "string", "Viewport source to capture", False, "viewport", ["viewport", "viewport_2d", "game", "cinematic"]),
                ("max_width", "integer", "Max image width in pixels", False, 1280, []),
                ("quality", "integer", "JPEG/PNG compression quality (1-100)", False, 80, []),
            ],
            aliases=["take_screenshot", "editor_screenshot"],
        ),
        op(
            "editor.logs.read",
            "Read Editor, Game, or Plugin Logs",
            "Read structured log entries from Godot editor output, running game, or plugin ring buffers with cursor tracking.",
            "editor",
            read_write=ReadWrite.READ,
            params=[
                ("source", "string", "Log stream source", False, "all", ["all", "editor", "game", "plugin"]),
                ("since_cursor", "integer", "Read logs recorded after this cursor index", False, 0, []),
                ("include_details", "boolean", "Include callstack and source file metadata", False, True, []),
                ("limit", "integer", "Maximum number of lines to return", False, 100, []),
            ],
            aliases=["logs_read", "get_logs"],
        ),
        op(
            "editor.logs.clear",
            "Clear Log Buffers",
            "Clear log buffers and optionally reset the Debugger dock Errors tab counters.",
            "editor",
            read_write=ReadWrite.WRITE,
            params=[("clear_debugger_errors", "boolean", "Also clear visible Debugger dock errors", False, False, [])],
            aliases=["clear_logs", "logs_clear"],
        ),
        op(
            "editor.monitors.get",
            "Get Performance Monitors",
            "Retrieve engine performance metrics including FPS, frame time, draw calls, memory usage, and node counts.",
            "editor",
            read_write=ReadWrite.READ,
            aliases=["get_performance_monitors", "performance_get_monitors"],
        ),
        op(
            "editor.plugin.reload",
            "Reload Godot AI / Omni Plugin",
            "Force the Godot editor to reload the Omni plugin scripts and re-establish the WebSocket bridge.",
            "editor",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            aliases=["reload_plugin", "editor_reload_plugin"],
        ),
        op(
            "editor.quit",
            "Quit Godot Editor",
            "Gracefully request the Godot editor process to close.",
            "editor",
            read_write=ReadWrite.WRITE,
            aliases=["quit_editor", "editor_quit"],
        ),

        # --- SCENE ---
        op(
            "scene.create",
            "Create New Scene File",
            "Create a new scene (.tscn) with a specified root node type and name.",
            "scene",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[
                ("path", "string", "res:// path for the new scene file", True, None, []),
                ("root_type", "string", "Node class for the scene root", True, "Node2D", []),
                ("root_name", "string", "Name for the root node", False, "Main", []),
            ],
            aliases=["create_scene", "scene_create"],
        ),
        op(
            "scene.open",
            "Open Scene in Editor",
            "Open an existing scene (.tscn) in the Godot editor.",
            "scene",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[("path", "string", "res:// path of the scene to open", True, None, [])],
            aliases=["open_scene", "scene_open"],
        ),
        op(
            "scene.save",
            "Save Currently Edited Scene",
            "Save the active scene in the editor to its disk file.",
            "scene",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            aliases=["save_scene", "scene_save"],
        ),
        op(
            "scene.save_as",
            "Save Current Scene As New Path",
            "Save the active scene under a new res:// path.",
            "scene",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[("path", "string", "New res:// path to save the scene to", True, None, [])],
            aliases=["save_scene_as", "scene_save_as"],
        ),
        op(
            "scene.close",
            "Close Currently Edited Scene",
            "Close the current scene tab in the Godot editor.",
            "scene",
            read_write=ReadWrite.WRITE,
            aliases=["close_scene", "scene_close"],
        ),
        op(
            "scene.get_hierarchy",
            "Get Paginated Scene Hierarchy Tree",
            "Retrieve hierarchical tree representation of nodes in the edited scene with depth, offset, and limit control.",
            "scene",
            read_write=ReadWrite.READ,
            params=[
                ("root_path", "string", "Starting node path (empty for scene root)", False, "", []),
                ("max_depth", "integer", "Maximum traversal depth (-1 for unlimited)", False, -1, []),
                ("offset", "integer", "Pagination offset", False, 0, []),
                ("limit", "integer", "Maximum nodes to return", False, 100, []),
            ],
            aliases=["get_scene_tree", "scene_get_hierarchy"],
        ),
        op(
            "scene.get_open_scenes",
            "List All Open Scene Tabs",
            "Retrieve the list of all scenes currently opened in editor tabs.",
            "scene",
            read_write=ReadWrite.READ,
            aliases=["get_open_scenes", "scene_get_open_scenes"],
        ),
        op(
            "scene.instantiate",
            "Instantiate Subscene Child",
            "Instantiate an existing .tscn file as a child of a node in the current scene.",
            "scene",
            read_write=ReadWrite.WRITE,
            params=[
                ("scene_path", "string", "res:// path of the scene to instantiate", True, None, []),
                ("parent_path", "string", "Node path where child should be added", False, "", []),
                ("name", "string", "Optional name for the instantiated node", False, "", []),
            ],
            aliases=["instantiate_scene", "scene_instantiate"],
        ),
        op(
            "scene.inherit",
            "Create Inherited Scene",
            "Create a new scene that inherits from a base scene.",
            "scene",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[
                ("base_scene_path", "string", "res:// path of base scene", True, None, []),
                ("new_scene_path", "string", "res:// path for new inherited scene", True, None, []),
            ],
            aliases=["inherit_scene", "scene_inherit"],
        ),
        op(
            "scene.validate",
            "Validate Scene Integrity",
            "Inspect a scene for broken dependencies, missing resources, or node configuration warnings.",
            "scene",
            read_write=ReadWrite.READ,
            params=[("path", "string", "res:// scene path (empty for current)", False, "", [])],
            aliases=["validate_scene", "scene_validate"],
        ),
        op(
            "scene.diff",
            "Compute Scene Modification Diff",
            "Calculate node and property differences between current in-memory scene and on-disk file.",
            "scene",
            read_write=ReadWrite.READ,
            aliases=["scene_diff"],
        ),
        op(
            "scene.snapshot",
            "Create Scene In-Memory Snapshot",
            "Create a restorable in-memory snapshot of the current scene state before complex modifications.",
            "scene",
            read_write=ReadWrite.WRITE,
            aliases=["scene_snapshot"],
        ),
        op(
            "scene.restore",
            "Restore Scene Snapshot",
            "Restore the scene to a previously captured in-memory snapshot.",
            "scene",
            read_write=ReadWrite.WRITE,
            params=[("snapshot_id", "string", "ID of snapshot to restore", True, None, [])],
            aliases=["scene_restore"],
        ),

        # --- NODE ---
        op(
            "node.create",
            "Create Node in Scene",
            "Add a new node of any Godot class or custom script to the currently edited scene.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("type", "string", "Godot node class name (e.g. Sprite2D, Camera3D)", True, None, []),
                ("name", "string", "Name for the node", False, "", []),
                ("parent_path", "string", "Parent node path (defaults to root)", False, "", []),
                ("scene_file", "string", "Optional guard ensuring target scene matches", False, "", []),
            ],
            aliases=["create_node", "node_create"],
            examples=[("Add Camera3D", {"type": "Camera3D", "name": "PlayerCamera", "parent_path": "/Main/Player"}, {"created": "/Main/Player/PlayerCamera"})],
        ),
        op(
            "node.delete",
            "Delete Node from Scene",
            "Remove a node and its descendants from the current scene (undoable).",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Path of the node to delete", True, None, []),
                ("scene_file", "string", "Optional scene guard", False, "", []),
            ],
            aliases=["delete_node", "node_delete"],
        ),
        op(
            "node.duplicate",
            "Duplicate Node Subtree",
            "Deep-copy a node and its children as a sibling in the scene tree.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Path of the node to duplicate", True, None, []),
                ("new_name", "string", "Optional name for duplicate", False, "", []),
            ],
            aliases=["duplicate_node", "node_duplicate"],
        ),
        op(
            "node.rename",
            "Rename Node",
            "Rename an existing node in the current scene.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Path of node to rename", True, None, []),
                ("new_name", "string", "New name for the node", True, None, []),
            ],
            aliases=["rename_node", "node_rename"],
        ),
        op(
            "node.reparent",
            "Reparent Node",
            "Move a node to a new parent in the hierarchy while preserving its transform.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Path of node to reparent", True, None, []),
                ("new_parent_path", "string", "Path of new parent node", True, None, []),
                ("keep_global_transform", "boolean", "Maintain world position/rotation", False, True, []),
            ],
            aliases=["reparent_node", "node_reparent"],
        ),
        op(
            "node.move",
            "Reorder Node Among Siblings",
            "Change the child index of a node among its siblings (index 0 is first).",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Path of node to move", True, None, []),
                ("index", "integer", "New sibling index (0-based)", True, 0, []),
            ],
            aliases=["move_node", "node_move"],
        ),
        op(
            "node.find",
            "Find Nodes by Query",
            "Search for nodes in current scene matching a name pattern, type, or group.",
            "node",
            read_write=ReadWrite.READ,
            params=[
                ("name", "string", "Name substring to match", False, "", []),
                ("type", "string", "Class name or base class to match", False, "", []),
                ("group", "string", "Group membership to match", False, "", []),
            ],
            aliases=["find_nodes", "node_find"],
        ),
        op(
            "node.get_properties",
            "Get Node Properties",
            "Retrieve editor-visible properties for a node, with optional field filtering.",
            "node",
            read_write=ReadWrite.READ,
            params=[
                ("path", "string", "Node path in scene", True, None, []),
                ("fields", "array", "Optional list of property names to filter", False, None, []),
            ],
            aliases=["get_node_properties", "node_get_properties"],
        ),
        op(
            "node.set_property",
            "Set Node Property",
            "Set a property on a node by name with automatic type coercion (Vector, Color, etc.).",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Node path in scene", True, None, []),
                ("property", "string", "Property name to set", True, None, []),
                ("value", "any", "Value to assign", True, None, []),
            ],
            aliases=["set_property", "node_set_property"],
        ),
        op(
            "node.set_multiple_properties",
            "Set Multiple Node Properties",
            "Batch set multiple properties on a node in a single round trip.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Node path in scene", True, None, []),
                ("properties", "object", "Dictionary of property name -> value", True, None, []),
            ],
            aliases=["set_multiple_properties", "node_set_multiple_properties"],
        ),
        op(
            "node.reset_property",
            "Reset Property to Default",
            "Revert a node property back to its engine or class default value.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Node path in scene", True, None, []),
                ("property", "string", "Property name to reset", True, None, []),
            ],
            aliases=["reset_property", "node_reset_property"],
        ),
        op(
            "node.get_children",
            "Get Direct Children of Node",
            "List immediate child nodes including name, type, and path for each.",
            "node",
            read_write=ReadWrite.READ,
            params=[("path", "string", "Parent node path", True, None, [])],
            aliases=["get_children", "node_get_children"],
        ),
        op(
            "node.groups.list",
            "List Groups of Node",
            "List all group names that the node is a member of.",
            "node",
            read_write=ReadWrite.READ,
            params=[("path", "string", "Node path", True, None, [])],
            aliases=["get_groups", "node_get_groups"],
        ),
        op(
            "node.groups.add",
            "Add Node to Group",
            "Add a node to a scene group.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Node path", True, None, []),
                ("group", "string", "Group name", True, None, []),
            ],
            aliases=["add_to_group", "node_add_to_group"],
        ),
        op(
            "node.groups.remove",
            "Remove Node from Group",
            "Remove a node from a scene group.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("path", "string", "Node path", True, None, []),
                ("group", "string", "Group name", True, None, []),
            ],
            aliases=["remove_from_group", "node_remove_from_group"],
        ),
        op(
            "node.signals.list",
            "List Node Signals & Connections",
            "List signals declared by a node class and active signal connections.",
            "node",
            read_write=ReadWrite.READ,
            params=[("path", "string", "Node path", True, None, [])],
            aliases=["list_signals", "node_list_signals"],
        ),
        op(
            "node.signals.connect",
            "Connect Signal to Method",
            "Wire a node signal to a target node method.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("source_path", "string", "Node emitting signal", True, None, []),
                ("signal_name", "string", "Name of the signal", True, None, []),
                ("target_path", "string", "Node receiving signal", True, None, []),
                ("method_name", "string", "Target method name", True, None, []),
                ("flags", "integer", "Connection flags (e.g. CONNECT_DEFERRED=1, CONNECT_ONE_SHOT=4)", False, 0, []),
            ],
            aliases=["connect_signal", "node_connect_signal"],
        ),
        op(
            "node.signals.disconnect",
            "Disconnect Signal",
            "Disconnect an existing signal connection between nodes.",
            "node",
            read_write=ReadWrite.WRITE,
            params=[
                ("source_path", "string", "Node emitting signal", True, None, []),
                ("signal_name", "string", "Name of the signal", True, None, []),
                ("target_path", "string", "Node receiving signal", True, None, []),
                ("method_name", "string", "Target method name", True, None, []),
            ],
            aliases=["disconnect_signal", "node_disconnect_signal"],
        ),

        # --- SCRIPT ---
        op(
            "script.create",
            "Create GDScript File",
            "Create a new GDScript (.gd) file with inheritance, templates, and syntax verification.",
            "script",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[
                ("path", "string", "res:// path for the script file", True, None, []),
                ("content", "string", "GDScript source code content", True, None, []),
                ("inherits", "string", "Base class name (e.g. Node3D, CharacterBody3D)", False, "Node", []),
            ],
            aliases=["create_script", "script_create"],
        ),
        op(
            "script.read",
            "Read Script Source Code",
            "Read the source text of a GDScript file.",
            "script",
            read_write=ReadWrite.READ,
            params=[("path", "string", "res:// path to script file", True, None, [])],
            aliases=["read_script", "script_read"],
        ),
        op(
            "script.patch",
            "Anchor-Based Script Patch",
            "Safely patch a section of a GDScript file using anchor search/replace with indentation protection.",
            "script",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[
                ("path", "string", "res:// path to script file", True, None, []),
                ("target", "string", "Exact code block to replace", True, None, []),
                ("replacement", "string", "New code block to insert", True, None, []),
            ],
            aliases=["patch_script", "script_patch"],
        ),
        op(
            "script.attach",
            "Attach Script to Node",
            "Attach an existing GDScript file to a node in the scene.",
            "script",
            read_write=ReadWrite.WRITE,
            params=[
                ("node_path", "string", "Node path in scene", True, None, []),
                ("script_path", "string", "res:// path of the script to attach", True, None, []),
            ],
            aliases=["attach_script", "script_attach"],
        ),
        op(
            "script.detach",
            "Detach Script from Node",
            "Detach and remove script reference from a node in the scene.",
            "script",
            read_write=ReadWrite.WRITE,
            params=[("node_path", "string", "Node path in scene", True, None, [])],
            aliases=["detach_script", "script_detach"],
        ),
        op(
            "script.symbols.find",
            "Find Script Symbols & AST",
            "Extract functions, variables, signals, annotations, and exports declared in a script.",
            "script",
            read_write=ReadWrite.READ,
            params=[("path", "string", "res:// path to script file", True, None, [])],
            aliases=["find_symbols", "script_find_symbols"],
        ),
        op(
            "script.validate",
            "Validate Script Syntax & Diagnostics",
            "Parse and validate GDScript syntax, returning line-numbered errors and warnings without writing to disk.",
            "script",
            read_write=ReadWrite.READ,
            params=[
                ("path", "string", "res:// path to script", False, "", []),
                ("content", "string", "Optional in-memory script content to validate", False, "", []),
            ],
            aliases=["validate_script", "script_validate"],
        ),

        # --- RESOURCE ---
        op(
            "resource.create",
            "Create Resource File",
            "Instantiate and save a new Godot Resource (.tres) to disk.",
            "resource",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[
                ("type", "string", "Resource class name (e.g. StandardMaterial3D, AudioStreamWAV)", True, None, []),
                ("path", "string", "res:// path where resource should be saved", True, None, []),
                ("properties", "object", "Initial property values", False, {}, []),
            ],
            aliases=["create_resource", "resource_create"],
        ),
        op(
            "resource.load",
            "Load Resource Data",
            "Load and inspect properties of an existing resource (.tres, .res).",
            "resource",
            read_write=ReadWrite.READ,
            params=[("path", "string", "res:// path to resource", True, None, [])],
            aliases=["load_resource", "resource_load"],
        ),
        op(
            "resource.assign",
            "Assign Resource to Node Property",
            "Assign a resource by path to a node property (e.g. assigning a material to MeshInstance3D.material_override).",
            "resource",
            read_write=ReadWrite.WRITE,
            params=[
                ("node_path", "string", "Target node path", True, None, []),
                ("property", "string", "Property name on node", True, None, []),
                ("resource_path", "string", "res:// path of the resource", True, None, []),
            ],
            aliases=["assign_resource", "resource_assign"],
        ),
        op(
            "resource.search",
            "Search Project Resources",
            "Search for resources matching a type or path pattern across the project.",
            "resource",
            read_write=ReadWrite.READ,
            params=[
                ("type", "string", "Resource class type filter", False, "", []),
                ("pattern", "string", "Glob pattern filter", False, "", []),
            ],
            aliases=["search_resources", "resource_search"],
        ),
        op(
            "resource.inspect",
            "Inspect Resource Sub-objects",
            "Inspect external and subresources embedded in a resource or scene file.",
            "resource",
            read_write=ReadWrite.READ,
            params=[("path", "string", "res:// path to resource or scene", True, None, [])],
            aliases=["inspect_resource", "resource_inspect"],
        ),

        # --- FILESYSTEM ---
        op(
            "filesystem.read_text",
            "Read Text File from res://",
            "Read UTF-8 text file from the project directory using res:// path.",
            "filesystem",
            read_write=ReadWrite.READ,
            latency_tier=LatencyTier.DISK,
            params=[("path", "string", "res:// file path", True, None, [])],
            aliases=["read_file", "filesystem_read_text"],
        ),
        op(
            "filesystem.write_text",
            "Write Text File to res://",
            "Write text content to a project file atomically with automatic directory creation.",
            "filesystem",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[
                ("path", "string", "res:// file path", True, None, []),
                ("content", "string", "File text contents", True, None, []),
            ],
            aliases=["write_file", "filesystem_write_text"],
        ),
        op(
            "filesystem.scan",
            "Scan Filesystem & Update Editor",
            "Request the Godot editor to rescan the filesystem dock and detect external file modifications.",
            "filesystem",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.IMPORT,
            aliases=["scan_filesystem", "filesystem_scan"],
        ),
        op(
            "filesystem.reimport",
            "Request Asset Reimport",
            "Trigger reimport of an asset file (texture, 3D model, sound).",
            "filesystem",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.IMPORT,
            params=[("path", "string", "res:// path of asset to reimport", True, None, [])],
            aliases=["reimport", "filesystem_reimport"],
        ),
        op(
            "filesystem.list",
            "List Directory Contents",
            "List files and subdirectories inside a project folder.",
            "filesystem",
            read_write=ReadWrite.READ,
            latency_tier=LatencyTier.DISK,
            params=[("path", "string", "res:// directory path", False, "res://", [])],
            aliases=["list_directory", "filesystem_list"],
        ),
        op(
            "filesystem.delete",
            "Delete File or Directory",
            "Safely delete a file or directory within res://.",
            "filesystem",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[("path", "string", "res:// path to delete", True, None, [])],
            aliases=["delete_file", "filesystem_delete"],
        ),
        op(
            "filesystem.move",
            "Move or Rename File",
            "Move or rename a file or directory within res://.",
            "filesystem",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[
                ("from_path", "string", "Source res:// path", True, None, []),
                ("to_path", "string", "Destination res:// path", True, None, []),
            ],
            aliases=["move_file", "filesystem_move"],
        ),

        # --- PROJECT ---
        op(
            "project.get_setting",
            "Get Project Setting",
            "Read a setting value from project.godot (e.g. display/window/size/viewport_width).",
            "project",
            read_write=ReadWrite.READ,
            params=[("setting", "string", "Setting key path", True, None, [])],
            aliases=["get_project_setting", "project_get_setting"],
        ),
        op(
            "project.set_setting",
            "Set Project Setting",
            "Update or create a setting in project.godot.",
            "project",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[
                ("setting", "string", "Setting key path", True, None, []),
                ("value", "any", "Value to assign", True, None, []),
            ],
            aliases=["set_project_setting", "project_set_setting"],
        ),
        op(
            "project.set_main_scene",
            "Set Project Main Scene",
            "Configure application/run/main_scene in project.godot.",
            "project",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.DISK,
            params=[("scene_path", "string", "res:// path of main scene", True, None, [])],
            aliases=["set_main_scene", "project_set_main_scene"],
        ),
        op(
            "project.run",
            "Launch Project in Game Mode",
            "Run the project or current scene and monitor game liveness and errors.",
            "project",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.RUNTIME,
            params=[
                ("scene_path", "string", "Optional specific scene to run (empty for main)", False, "", []),
                ("autosave", "boolean", "Save modified scenes before launching", False, True, []),
            ],
            aliases=["project_run", "run_project"],
        ),
        op(
            "project.stop",
            "Stop Running Game",
            "Terminate the running game process launched from the editor.",
            "project",
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.RUNTIME,
            aliases=["project_stop", "stop_project"],
        ),

        # --- NODE OWNERSHIP & METADATA (EXTENDED) ---
        op("node.get_owner", "Get Node Scene Owner", "Get the node path of the scene owner for this node.", "node", read_write=ReadWrite.READ, params=[("path", "string", "Node path", True, None, [])]),
        op("node.set_owner", "Set Node Scene Owner", "Set the scene root as owner so this node persists when saving the scene.", "node", read_write=ReadWrite.WRITE, params=[("path", "string", "Node path", True, None, []), ("owner_path", "string", "Scene root path", True, None, [])]),
        op("node.set_unique_name", "Set Scene Unique Name (%Node)", "Enable or disable unique name in owner (%Name) for fast access.", "node", read_write=ReadWrite.WRITE, params=[("path", "string", "Node path", True, None, []), ("enabled", "boolean", "Enable unique name", False, True, [])]),
        op("node.get_warnings", "Get Node Configuration Warnings", "Retrieve editor configuration warnings (yellow caution badge) for a node.", "node", read_write=ReadWrite.READ, params=[("path", "string", "Node path", True, None, [])]),
        op("node.metadata.get", "Get Node Metadata", "Read custom metadata key from a node.", "node", read_write=ReadWrite.READ, params=[("path", "string", "Node path", True, None, []), ("key", "string", "Metadata key name", True, None, [])]),
        op("node.metadata.set", "Set Node Metadata", "Assign custom metadata key-value pair to a node.", "node", read_write=ReadWrite.WRITE, params=[("path", "string", "Node path", True, None, []), ("key", "string", "Metadata key name", True, None, []), ("value", "any", "Metadata value", True, None, [])]),
        op("node.metadata.remove", "Remove Node Metadata", "Erase custom metadata key from a node.", "node", read_write=ReadWrite.WRITE, params=[("path", "string", "Node path", True, None, []), ("key", "string", "Metadata key to erase", True, None, [])]),

        # --- SCENE DEPENDENCIES (EXTENDED) ---
        op("scene.dependencies.list", "List Scene External Dependencies", "Inspect all external scenes, textures, sounds, and resources referenced by a scene.", "scene", read_write=ReadWrite.READ, params=[("scene_path", "string", "res:// scene path", True, None, [])]),
        op("scene.dependencies.replace", "Replace Scene Dependency Path", "Remap or update an external dependency reference in a .tscn file.", "scene", read_write=ReadWrite.WRITE, latency_tier=LatencyTier.DISK, params=[("scene_path", "string", "res:// scene path", True, None, []), ("old_path", "string", "Old resource path", True, None, []), ("new_path", "string", "New resource path", True, None, [])]),

        # --- SCRIPT INTROSPECTION (EXTENDED) ---
        op("script.get_class_name", "Get Script Registered class_name", "Extract class_name and icon declared in a script header.", "script", read_write=ReadWrite.READ, params=[("path", "string", "res:// script path", True, None, [])]),
        op("script.reload", "Reload Script in Engine", "Force the engine and editor to recompile and reload a modified script.", "script", read_write=ReadWrite.WRITE, params=[("path", "string", "res:// script path", True, None, [])]),

        # --- FILESYSTEM UTILITIES (EXTENDED) ---
        op("filesystem.stat", "Get File Metadata & Size", "Retrieve file size, modified timestamp, and read/write flags.", "filesystem", read_write=ReadWrite.READ, latency_tier=LatencyTier.DISK, params=[("path", "string", "res:// path", True, None, [])]),
        op("filesystem.copy", "Copy File in Project", "Copy a file from one res:// location to another.", "filesystem", read_write=ReadWrite.WRITE, latency_tier=LatencyTier.DISK, params=[("from_path", "string", "Source path", True, None, []), ("to_path", "string", "Destination path", True, None, [])]),
        op("filesystem.create_directory", "Create Directory Folder", "Create a folder and any missing parent directories in res://.", "filesystem", read_write=ReadWrite.WRITE, latency_tier=LatencyTier.DISK, params=[("path", "string", "res:// directory path", True, None, [])]),
        op("filesystem.hash_file", "Compute SHA256 Hash of File", "Calculate cryptographic hash of a project file for change detection.", "filesystem", read_write=ReadWrite.READ, latency_tier=LatencyTier.DISK, params=[("path", "string", "res:// path", True, None, [])]),

        # --- PROJECT METADATA (EXTENDED) ---
        op("project.get_features", "Get Engine Feature Tags", "Retrieve active Godot feature tags (e.g. windows, 64, double_precision, etc.).", "project", read_write=ReadWrite.READ),
        op("project.change_icon", "Change Project Main Icon", "Set application/config/icon in project.godot.", "project", read_write=ReadWrite.WRITE, latency_tier=LatencyTier.DISK, params=[("icon_path", "string", "res:// path to icon image", True, None, [])]),
    ]
    return ops
