"""Runtime Game Operations (Comprehensive Suite: 56+ Operations)."""

from __future__ import annotations

from godot_omni.operations.builder import op
from godot_omni.registry.models import (
    CanonicalOperation,
    ExecutionContext,
    LatencyTier,
    OperationCategory,
    ReadWrite,
)


def get_runtime_operations() -> list[CanonicalOperation]:
    ops: list[CanonicalOperation] = [
        op(
            "game.status",
            "Get Game Liveness & Status",
            "Check if running game process is live, paused, crashed, or waiting at a debugger break.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.READ,
            execution_context=ExecutionContext.BOTH,
            aliases=["game_status", "get_game_status"],
        ),
        op(
            "game.eval",
            "Evaluate GDScript in Running Game",
            "Execute an arbitrary GDScript expression inside the live running game and return the evaluated result.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            latency_tier=LatencyTier.RUNTIME,
            params=[("expression", "string", "GDScript code snippet or expression to evaluate", True, None, [])],
            aliases=["game_eval", "eval_in_game"],
        ),
        op(
            "game.node.call_method",
            "Call Method on Runtime Node",
            "Invoke a method on a node in the running game's live scene tree.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            latency_tier=LatencyTier.RUNTIME,
            params=[
                ("node_path", "string", "Absolute path in running game (e.g. '/root/Main/Player')", True, None, []),
                ("method", "string", "Method name to invoke", True, None, []),
                ("args", "array", "Arguments list", False, [], []),
            ],
            aliases=["game_call_method", "runtime_call_method"],
        ),
        op(
            "game.node.get_property",
            "Get Property of Runtime Node",
            "Read dynamic property value from a node in the running game.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.READ,
            execution_context=ExecutionContext.RUNTIME,
            params=[
                ("node_path", "string", "Absolute path in running game", True, None, []),
                ("property", "string", "Property name to read", True, None, []),
            ],
            aliases=["game_get_property", "runtime_get_property"],
        ),
        op(
            "game.node.set_property",
            "Set Property on Runtime Node",
            "Assign property value to a node in the running game.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            params=[
                ("node_path", "string", "Absolute path in running game", True, None, []),
                ("property", "string", "Property name to set", True, None, []),
                ("value", "any", "Value to assign", True, None, []),
            ],
            aliases=["game_set_property", "runtime_set_property"],
        ),
        op(
            "game.scene.get_tree",
            "Get Runtime Live Scene Tree",
            "Walk and return the live scene tree of the running game process starting at /root.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.READ,
            execution_context=ExecutionContext.RUNTIME,
            aliases=["game_get_tree", "runtime_get_tree"],
        ),
        op(
            "game.pause",
            "Pause Game Simulation",
            "Pause the game loop using SceneTree.paused = true.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            aliases=["game_pause"],
        ),
        op(
            "game.resume",
            "Resume Game Simulation",
            "Unpause the game loop using SceneTree.paused = false.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            aliases=["game_resume"],
        ),
        op(
            "game.frame.advance",
            "Advance Game Simulation Frames",
            "Step the running game forward by N frames while in debug pause mode.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[("frames", "integer", "Number of frames to advance", False, 1, [])],
            aliases=["game_advance_frames", "step_frames"],
        ),
        op(
            "game.screenshot",
            "Capture Running Game Framebuffer",
            "Grab the exact rendered framebuffer texture of the game viewport.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.READ,
            execution_context=ExecutionContext.RUNTIME,
            latency_tier=LatencyTier.FRAME_BOUND,
            aliases=["game_screenshot"],
        ),
        op(
            "game.performance.snapshot",
            "Capture Game Performance Snapshot",
            "Retrieve FPS, physics time, process time, draw calls, and memory from running game.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.READ,
            execution_context=ExecutionContext.RUNTIME,
            aliases=["game_performance_snapshot"],
        ),
        op(
            "game.performance.sample_interval",
            "Sample Performance over Time",
            "Record running game performance metrics over a duration (e.g. 5 seconds) and return statistics (p50, p95, min, max, avg).",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.READ,
            execution_context=ExecutionContext.RUNTIME,
            latency_tier=LatencyTier.LONG_JOB,
            params=[("duration_seconds", "number", "Sample duration in seconds", False, 5.0, [])],
            aliases=["game_sample_performance"],
        ),

        # --- RUNTIME INPUT SIMULATION ---
        op(
            "game.input.press_key",
            "Simulate Key Press in Game",
            "Send a key down or tap event to the running game.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            latency_tier=LatencyTier.RUNTIME,
            params=[
                ("key", "string", "Key name (e.g. W, Space, Escape, Shift)", True, None, []),
                ("press_type", "string", "Event type", False, "tap", ["tap", "down", "up"]),
            ],
            aliases=["game_press_key", "simulate_key"],
        ),
        op(
            "game.input.release_key",
            "Simulate Key Release in Game",
            "Send a key release (up) event to the running game.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            params=[("key", "string", "Key name", True, None, [])],
            aliases=["game_release_key"],
        ),
        op(
            "game.input.move_mouse",
            "Simulate Mouse Move in Game",
            "Move the virtual mouse cursor to coordinate position in the game viewport.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            latency_tier=LatencyTier.RUNTIME,
            params=[
                ("position", "array", "Target coordinates [x, y]", True, None, []),
                ("relative", "array", "Optional relative delta [dx, dy]", False, [0, 0], []),
            ],
            aliases=["game_move_mouse", "simulate_mouse_move"],
        ),
        op(
            "game.input.mouse_button",
            "Simulate Mouse Button Click in Game",
            "Press or release mouse button in game.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            params=[
                ("button_index", "integer", "1=Left, 2=Right, 3=Middle", True, 1, []),
                ("pressed", "boolean", "Pressed state", True, True, []),
            ],
            aliases=["game_mouse_button"],
        ),
        op(
            "game.input.mouse_wheel",
            "Simulate Mouse Wheel Scroll in Game",
            "Scroll mouse wheel up or down in game viewport.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            params=[("factor", "number", "Scroll delta factor", True, 1.0, [])],
            aliases=["game_mouse_wheel"],
        ),
        op(
            "game.input.send_action",
            "Trigger InputMap Action in Game",
            "Inject an InputEventAction (press or release) directly into Godot's Input singleton.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            latency_tier=LatencyTier.RUNTIME,
            params=[
                ("action", "string", "Action name (e.g. ui_accept, move_left)", True, None, []),
                ("pressed", "boolean", "True for press, False for release", False, True, []),
                ("strength", "number", "Analog strength (0.0 to 1.0)", False, 1.0, []),
            ],
            aliases=["game_send_action", "trigger_input_action"],
        ),
        op(
            "game.input.joypad_button",
            "Simulate Gamepad Button in Game",
            "Inject a gamepad button press/release event.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            params=[
                ("button_index", "integer", "Joypad button enum index", True, None, []),
                ("pressed", "boolean", "Pressed state", True, True, []),
            ],
            aliases=["game_joypad_button"],
        ),
        op(
            "game.input.joypad_axis",
            "Simulate Gamepad Analog Axis",
            "Inject analog joystick axis position (-1.0 to 1.0).",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            params=[
                ("axis", "integer", "Axis index (0=LeftX, 1=LeftY, 2=RightX, 3=RightY)", True, None, []),
                ("value", "number", "Axis deflection from -1.0 to 1.0", True, None, []),
            ],
            aliases=["game_joypad_axis"],
        ),
        op(
            "game.input.execute_sequence",
            "Execute Timed Gameplay Input Script",
            "Run a deterministic sequence of timed input actions across multiple frames.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.WRITE,
            execution_context=ExecutionContext.RUNTIME,
            latency_tier=LatencyTier.RUNTIME,
            params=[("sequence", "array", "List of event items with {action/key, state, frame/ms}", True, None, [])],
            aliases=["game_execute_sequence", "run_input_script"],
        ),
        op(
            "game.physics.get_direct_state_2d",
            "Get 2D Direct Physics State",
            "Query 2D physics space state for raycasts and point checks in game.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.READ,
            execution_context=ExecutionContext.RUNTIME,
            aliases=["game_physics_state_2d"],
        ),
        op(
            "game.physics.get_direct_state_3d",
            "Get 3D Direct Physics State",
            "Query 3D physics space state for raycasts and shape casts in game.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.READ,
            execution_context=ExecutionContext.RUNTIME,
            aliases=["game_physics_state_3d"],
        ),
        op(
            "game.physics.raycast_3d",
            "Perform Live 3D Raycast in Game",
            "Cast a ray in running game world and return hit collider, position, and normal.",
            "game",
            category=OperationCategory.RUNTIME,
            read_write=ReadWrite.READ,
            execution_context=ExecutionContext.RUNTIME,
            params=[
                ("from_pos", "array", "Ray start [x, y, z]", True, None, []),
                ("to_pos", "array", "Ray end [x, y, z]", True, None, []),
                ("collision_mask", "integer", "Mask bitmask", False, 4294967295, []),
            ],
            aliases=["game_raycast_3d"],
        ),
    ]

    # Expand with named game actions and control operations
    named_actions = [
        "move_forward", "move_backward", "move_left", "move_right", "jump", "crouch", "sprint",
        "interact", "fire", "alt_fire", "reload", "pause", "inventory", "ui_accept", "ui_cancel",
        "ui_up", "ui_down", "ui_left", "ui_right", "ui_focus_next", "ui_focus_prev",
    ]
    for action in named_actions:
        ops.append(
            op(
                f"game.action.{action}.press",
                f"Press Action: {action}",
                f"Simulate pressing the '{action}' action in the running game.",
                "game",
                category=OperationCategory.RUNTIME,
                read_write=ReadWrite.WRITE,
                execution_context=ExecutionContext.RUNTIME,
                aliases=[f"action_{action}_press"],
            )
        )
        ops.append(
            op(
                f"game.action.{action}.release",
                f"Release Action: {action}",
                f"Simulate releasing the '{action}' action in the running game.",
                "game",
                category=OperationCategory.RUNTIME,
                read_write=ReadWrite.WRITE,
                execution_context=ExecutionContext.RUNTIME,
                aliases=[f"action_{action}_release"],
            )
        )

    return ops
