"""Editor UI Semantic Tree & Input Automation Operations (Comprehensive Catalog)."""

from __future__ import annotations

from godot_omni.operations.builder import op
from godot_omni.registry.models import (
    CanonicalOperation,
    LatencyTier,
    OperationCategory,
    ReadWrite,
)


def get_ui_automation_operations() -> list[CanonicalOperation]:
    ops: list[CanonicalOperation] = [
        op(
            "editor_ui.get_semantic_tree",
            "Get Editor UI Semantic Tree",
            "Traverse editor Control hierarchy and return structured UI elements with semantic IDs, classes, labels, and bounding boxes.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.READ,
            params=[
                ("root_selector", "string", "Optional container selector (e.g. 'dock/inspector', 'dock/filesystem')", False, "", []),
                ("max_depth", "integer", "Max UI traversal depth", False, 6, []),
                ("visible_only", "boolean", "Omit hidden controls", False, True, []),
            ],
            aliases=["editor_ui_get_tree", "get_editor_ui_tree"],
        ),
        op(
            "editor_ui.find_element",
            "Find Editor UI Element by Semantic Query",
            "Locate buttons, tabs, line edits, or menus in the editor by label text, tooltip, or UI ID.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.READ,
            params=[
                ("query", "string", "Text or tooltip substring to match", True, None, []),
                ("control_type", "string", "Optional Control class filter (e.g. Button, LineEdit, TabBar)", False, "", []),
            ],
            aliases=["editor_ui_find", "find_editor_element"],
        ),
        op(
            "editor_ui.click",
            "Click Editor UI Element",
            "Simulate a mouse click on an editor UI element using semantic ID, text match, or coordinates fallback.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[
                ("target", "string", "Semantic UI ID ('ui://...') or button text label", True, None, []),
                ("button", "string", "Mouse button to click", False, "left", ["left", "right", "middle"]),
                ("double_click", "boolean", "Perform double click", False, False, []),
            ],
            aliases=["editor_ui_click", "click_editor_element"],
        ),
        op(
            "editor_ui.double_click",
            "Double-Click Editor UI Element",
            "Perform a double-click on an editor UI element.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[("target", "string", "Semantic UI ID or text", True, None, [])],
            aliases=["editor_ui_double_click"],
        ),
        op(
            "editor_ui.right_click",
            "Right-Click Editor UI Element (Context Menu)",
            "Trigger a right-click context menu on an editor element.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[("target", "string", "Semantic UI ID or text", True, None, [])],
            aliases=["editor_ui_right_click"],
        ),
        op(
            "editor_ui.type_text",
            "Type Text into Editor Focus",
            "Simulate typing text characters into the currently focused editor input control.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[
                ("text", "string", "Text string to input", True, None, []),
                ("submit_enter", "boolean", "Press Enter key after typing", False, True, []),
            ],
            aliases=["editor_ui_type", "type_editor_text"],
        ),
        op(
            "editor_ui.send_shortcut",
            "Send Editor Keyboard Shortcut",
            "Send key combination or shortcut to the editor (e.g. 'ctrl+s', 'f5', 'ctrl+z', 'escape').",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[("shortcut", "string", "Shortcut descriptor string", True, None, [])],
            aliases=["editor_ui_shortcut", "send_editor_shortcut"],
        ),
        op(
            "editor_ui.key_down",
            "Simulate Key Down Event",
            "Send a raw key down event to the editor.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[("key", "string", "Key name", True, None, [])],
            aliases=["editor_ui_key_down"],
        ),
        op(
            "editor_ui.key_up",
            "Simulate Key Up Event",
            "Send a raw key up event to the editor.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[("key", "string", "Key name", True, None, [])],
            aliases=["editor_ui_key_up"],
        ),
        op(
            "editor_ui.drag_and_drop",
            "Perform Editor Drag and Drop",
            "Simulate dragging from a source control or file onto a target control or dock.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[
                ("from_target", "string", "Drag source element ID or path", True, None, []),
                ("to_target", "string", "Drop destination element ID or path", True, None, []),
            ],
            aliases=["editor_ui_drag_and_drop"],
        ),
        op(
            "editor_ui.scroll",
            "Scroll ScrollContainer or Dock",
            "Scroll a scrollable editor container vertically or horizontally.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[
                ("target", "string", "ScrollContainer ID", True, None, []),
                ("delta_y", "number", "Vertical scroll delta", False, 0.0, []),
                ("delta_x", "number", "Horizontal scroll delta", False, 0.0, []),
            ],
            aliases=["editor_ui_scroll"],
        ),
        op(
            "editor_ui.menu_list",
            "List Main Menu Items",
            "List items, submenus, and action IDs available in the Godot editor main menu bar.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.READ,
            params=[("menu_name", "string", "Top-level menu name (Scene, Project, Editor, Help)", False, "", [])],
            aliases=["editor_ui_menu_list", "list_editor_menus"],
        ),
        op(
            "editor_ui.menu_click",
            "Click Editor Menu Item",
            "Trigger a top-level menu action by path (e.g. 'Project/Project Settings...', 'Scene/New Scene').",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[("menu_path", "string", "Slash-separated menu path", True, None, [])],
            aliases=["editor_ui_menu_click", "click_editor_menu"],
        ),
        op(
            "editor_ui.context_menu_click",
            "Click Context Menu Item",
            "Click an option in an active popup or context menu.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[("item_text", "string", "Context menu item text", True, None, [])],
            aliases=["editor_ui_context_menu_click"],
        ),
        op(
            "editor_ui.command_palette_open",
            "Open Editor Command Palette",
            "Summon the Godot editor Command Palette (Ctrl+Shift+P).",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            aliases=["editor_ui_open_palette"],
        ),
        op(
            "editor_ui.command_palette_execute",
            "Execute Command Palette Action",
            "Search and trigger an action in the editor Command Palette.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[("command", "string", "Command title substring", True, None, [])],
            aliases=["editor_ui_execute_palette_command"],
        ),
        op(
            "editor_ui.dialog_get_active",
            "Inspect Active Modal Dialog",
            "Detect and inspect any currently open modal dialogs, confirmations, or file pickers.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.READ,
            aliases=["editor_ui_get_dialog", "get_active_dialog"],
        ),
        op(
            "editor_ui.dialog_confirm",
            "Confirm / Accept Active Dialog",
            "Trigger the OK / Confirm / Accept button on the active modal dialog.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            aliases=["editor_ui_confirm_dialog", "confirm_dialog"],
        ),
        op(
            "editor_ui.dialog_cancel",
            "Cancel / Dismiss Active Dialog",
            "Trigger the Cancel / Close button on the active modal dialog.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            aliases=["editor_ui_cancel_dialog", "cancel_dialog"],
        ),
        op(
            "editor_ui.dialog_fill_field",
            "Fill Field in Active Dialog",
            "Locate and input text into a named LineEdit inside the active dialog.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[
                ("field_name", "string", "Label or placeholder of field", True, None, []),
                ("value", "string", "Text value to fill", True, None, []),
            ],
            aliases=["editor_ui_dialog_fill"],
        ),
        op(
            "editor_ui.inspector_get_object",
            "Get Current Object in Inspector Dock",
            "Inspect the class and properties of the object currently loaded into the editor's Inspector dock.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.READ,
            aliases=["inspector_get_object", "editor_inspector_get"],
        ),
        op(
            "editor_ui.inspector_list_sections",
            "List Property Sections in Inspector",
            "List category and group sections currently visible in the Inspector.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.READ,
            aliases=["inspector_list_sections"],
        ),
        op(
            "editor_ui.inspector_expand_section",
            "Expand Inspector Section",
            "Expand a collapsed category section in the Inspector dock.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[("section_name", "string", "Section title", True, None, [])],
            aliases=["inspector_expand_section"],
        ),
        op(
            "editor_ui.inspector_collapse_section",
            "Collapse Inspector Section",
            "Collapse a category section in the Inspector dock.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[("section_name", "string", "Section title", True, None, [])],
            aliases=["inspector_collapse_section"],
        ),
        op(
            "editor_ui.inspector_set_property",
            "Set Property via Inspector Control",
            "Set a property directly through its editor Inspector widget.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[
                ("property_name", "string", "Property name", True, None, []),
                ("value", "any", "Value to assign", True, None, []),
            ],
            aliases=["inspector_set_property"],
        ),
        op(
            "editor_ui.dock_switch_tab",
            "Switch Dock Tab",
            "Switch the active tab in a dock container (e.g. Scene, Import, Node, History).",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[("tab_title", "string", "Tab title text", True, None, [])],
            aliases=["editor_ui_switch_tab"],
        ),
        op(
            "editor_ui.dock_focus",
            "Focus Editor Dock",
            "Move keyboard and mouse focus to a named editor dock.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[("dock_name", "string", "Dock name (e.g. 'FileSystem', 'Scene', 'Inspector')", True, None, [])],
            aliases=["editor_ui_focus_dock"],
        ),
        op(
            "editor_ui.filesystem_dock_reveal",
            "Reveal File in FileSystem Dock",
            "Select and reveal a file or folder in the editor's FileSystem dock.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            params=[("path", "string", "res:// path to reveal", True, None, [])],
            aliases=["filesystem_dock_reveal"],
        ),
        op(
            "editor_ui.accessibility.get_element",
            "OS Accessibility Fallback: Get UI Element",
            "Query the Godot editor window using OS accessibility APIs (Windows UIA / Linux AT-SPI / macOS Accessibility).",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.READ,
            params=[("selector", "string", "Accessibility name or role", True, None, [])],
            aliases=["accessibility_get_element"],
        ),
        op(
            "editor_ui.accessibility.click",
            "OS Accessibility Fallback: Click Element",
            "Invoke click on a Godot editor element via OS accessibility automation.",
            "editor_ui",
            category=OperationCategory.UI_AUTOMATION,
            read_write=ReadWrite.WRITE,
            latency_tier=LatencyTier.FRAME_BOUND,
            params=[("selector", "string", "Accessibility name or automation ID", True, None, [])],
            aliases=["accessibility_click"],
        ),
    ]

    # Additional programmatic operations for editor interaction across docks and panels
    editor_docks = ["Scene", "Import", "FileSystem", "Inspector", "Node", "History", "Output", "Debugger", "Audio", "Animation", "Shader", "TileMap"]
    for dock in editor_docks:
        ops.append(
            op(
                f"editor_ui.dock.{dock.lower()}.select",
                f"Select {dock} Dock",
                f"Make the {dock} dock visible and focused.",
                "editor_ui",
                category=OperationCategory.UI_AUTOMATION,
                read_write=ReadWrite.WRITE,
                aliases=[f"dock_{dock.lower()}_select"],
            )
        )
        ops.append(
            op(
                f"editor_ui.dock.{dock.lower()}.get_state",
                f"Get {dock} Dock State",
                f"Inspect controls and state of the {dock} dock.",
                "editor_ui",
                category=OperationCategory.UI_AUTOMATION,
                read_write=ReadWrite.READ,
                aliases=[f"dock_{dock.lower()}_get_state"],
            )
        )

    return ops
